//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootballManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FootballManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAKCElEQVR4Xu2cW0xcxxnH/7NggoNtwOuAMWAuwSW+oC5FqbHcJotc5SFRZSxVeYhqski9PPTB2aVq+1ZbfW28RmqrXiJlWaJKkaomVlu1qmNB0qS7ToqNhVtDwRgDNpd4YRezBgO7U82WpeyFPTNnz2WXnnlBcObM9833m++b+WbmQGAUXS1AdJVuCIcBQOdBYAAwAOhsAZ3FGx5gANDZAjqLNzzAAKCzBXQWb3iAAUBnC+gs3vCA/zcAbR9efD0coj8YHxzCk+XlXxNiuuy1u8bk2KHZaaumNHz6qfz871QdPjxHTPQt94uOLjlt6fWOJh5g63EWhU04BwobgGrW2Zl741jwzUX6TYExUPRSQvtNoP1rJCfwmd3Vv9kozzttllwaKgyDWAglFhBYyXpbe8x7UVp1MFp9DAQuUxidrha7Xy/D8spVFcBrPU5LDsE5gojhY8rqygrGbv2L [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string AddCl {
            get {
                return ResourceManager.GetString("AddCl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAVs0lEQVR4Xt2dD3BV1Z3Hz1XEP2hJBosiLgQLZavO8qIj9Q+UuESpWiaPIuyMrJJUS137hyijs9OZJQk7Ozujq3l06u623W4SWp2pQvMoTi2ImyBQHDo1YW3tUlkTulqVKZtE1G61enc+977f5byT+++9e98L9cwwJLn3nj+//7/v+d1zLVWFZtt2s1Kq88CBl96cPHnSRVde+cnPKKXq8vn9vaOjb6vm5mUtSqn88eNjz42NvTv7kktmvKKU2m5ZVnsVpjehQ1jVGN227Zp8fv8IY7W0PKh2737oBD83Nt5/Hv/39T2sZs2a/pulS++ftX79550pNTcvm2NZ1nA15jeRY1SFASzwxRdf2bV4cesNo6PvqJqaKaqu7kI1NPSGqqu7QI2NvaPQBK7RDhz4xq+vueay+RNJmGqNXTUGYIYymXVdDQ0LHEL39OxSudw9zjpbW/9ZLVnyF0i9 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string AddL {
            get {
                return ResourceManager.GetString("AddL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAM6klEQVR4Xu2dC3BU1RnH/2dfCZvEPACTECyQkABBJZjaCmhFYiUMggwkTI2VR7ViHRV8E2sVn4n1EWQYtaPWKL6GRAijLUkLERURESXaipCYB5IQIiHZvLPP0zl3syEbsrv3fbeyd2ZngPt93znn/zuve865F4LQpakCRNPUQ4kjBEDjShACEAKgsQIaJx9qASEAGiugcfKhFhACwF+B/NwFV7rgytBRTKQgGZwnwUQCTDwThVYBaHBRFD9dWrGDf3RtLIO6BTyY+9sMF9VfB2AuIZgrXCJaFma3rt5Qtsci3Fcdj6ADsGHJ3Jg+Y9hKHbAKnlouQQtKsaewtPwqCSEUdQ0aAEz4fkP4WgK6DoTEyFlqCqwuLCkvljOmXLGCAsD6nOy5IHjduy+Xq4gApXRHYWnFEvkiyhdJcwD5OfOLQMg6+Yo0cqSCknLNyzpSzjTLFOtyrMawj+To [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string AddPl {
            get {
                return ResourceManager.GetString("AddPl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAD70lEQVR4Xu2dT28SQRjG34Hlb6GwpfwpbWpd9e4H0AS/gTe/hRcTj9496MHEo4lX7n4AEz+Gxno0Gk9qPNk1A2wLuMs+MzAshWeTppfZGfj95n3YnYGsEh6ZElCZjs7BhQIyngQUQAEZE8h4eFYABZgRCAfiSev0VPJeILkwkAsViAoDCcf/1fD8wKzHbFtvZAWED8+aUri4Jbl8IGEYiFKBhBKIEg36VJR4SdjU8PNGvqfE15uF/7RZLKJ829dFARNyy8xiW/j6PAqIBDwKwmVA2p77+PcN21MTz6vu7cnz4Tsn0eakU/1Owi0RkM/npX9yIk9fv3XCykmn2ySg2+tJpVqVJ6/eOGHlpNNtEVCv16XVbo+iiQLAZF/VZ4DneaPoyeVyFACyHzVblYBevy/lcvlyaFYAaGEVAhqNhvit1syIFLAmAYViUfrHx6LU7McjBaxJgIZfLJX+ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAGQAAABkCAYAAABw4pVUAAAGL0lEQVR4Xu2cXUwcVRTHz7Ktu7XEQsTG2oYCLw1tUBBSu9QPUoutiS81URNJTH2xGp98UHfjQ+lLG4xfb+qLaIz1rU1MNHYXTas1JU1tWdYSeaDlo0oCNAJBBMrOmDvsrLO4zNwzM3fnDnNuQiDMuefe+//Nmbnn3pkJARWpFAhJ1RvqDBAQyU4CAkJAJFNAsu64EiFPnbrUGQrBccnGZtodFSB/vVZB7UvGW5tk6D8ByVGQBYrrQDr275DhRLPsQ//oLGTGZgvsZIDiOpDv395nKYYMBl9evAVf/XJL60o0EoaFxaz2t9dQCAgAvPNcA7z/zYAUUAgIAHzy6iMwdnteCigEJAeEXa5kgEJADEBkgEJAVgHxGgoBKQLESygEZA0gXkEhICZAvIBCQCyAlBoKAeEAUkooBIQTSKmgEBAEkFJAISBIIKKhEBAbQERCISA2gYiCQkAcABEB [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAR1ElEQVR4Xu1dS3AcRxn+e2d39bYlP6KkkjgKCVABCstAcuBRtjjElwRkKgdyIVmdqEhUpJLgGvsKEjZVUoqT1nCBA4llkks4xHJVkkMCRIYiDlV5yA5gO7b1fu5jmvp7d1YzPT07szM9O7M7M1WpuFY93T3///Xf/f/9PwjEj4ECk8OzzxEgJyhAPyHQLyQPhUUAmKdA55UUuTh2LrPSqGQkjTpxmfM+O5rtVvPwEhB4HgC6a+x7BSjMJYpwZuy3GQRGQz2RB8DkSPZFAnDaBeN5RqMUODc+nTnTSAiILABw1RfzcMlSzLvkIqWwoBThVKNIg0gC4JcvZPsVAheAQJ+Iz/meBOw8mIbd+5JQ7EhAoTPBmiVyFFLLRUgtFSF9Iw9t/ylYwWSlqMLAL17OLLjEUd1eixwAzv4026cm4X2RyN/tVWC9vw12e5OOGICA2PfuFnR8khe1bwgQ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string PluginIcon {
            get {
                return ResourceManager.GetString("PluginIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAGAAAABgCAYAAADimHc4AAAF0ElEQVR4Xu2dW0wcVRjH/8NWut2CQW62sqHUkoK8WJNaU1sVU3zxknh7QI0JNLFqNBor1tQXrdE0sbCxMUJ8QNCYtAkxeHtTtBqpSnxAQ0xpVNoEigWFZUtlu8CMGWDpMszsnjPnzM6M/Uh4gPm+c/n9zmVuLAroy1UCiqu1U+UgAS4PAhJAAlwm4HL1NANIgMsEXK6eZgAJcJmAy9XTDPCLgOk9OzSztv46EuPqwlhrO1e8U8F1b75gWrSm4VD+132vOVWvsVzmGXClCNABZVMCCbAY6tmSQALSrDXZkOBbAQeaXky7TL/V3JL2uNUeYExyWgIJYNhtnZRAAhgEOLkxkwBGAU5JIAEcApyQQAI4BciWQAJsCNBT8nr6mNmlq4K5EK9dCWfrNNQKHgnI0nUACbAgQDNgCYxbd0NJAAlg3j9pEzYhwHoviPYA2gMWCVidhg6ci0E1fVZm [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAARTQAAEU0BwDlgYwAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA+iSURBVHic7ZtpkFzVdcd/973X6/TMaBZpRgta0S4QEiDhcRTbShlsGRuREFVhUgHkMlSQhIVkUo5JpSZV+ZDYgIxAGFWlEGAc4tgJJuxQAYGRkRSCQKxaR8tom71nenv93rs3H153q2c0UnfP65FY5v+p3+27nPt/55577rnnwQhGMIIRjGAEIxjB5xLifA/Y3Pwf/khb3yKhickKRgsl/EqQ0JTqFfBBdHTkw+bmFenzLddQcV4I3LjmySoL6walxI1C8FWUCp2jeloh3tTg34Wh/vOuX9zacz5kHCqGlcCNa56sslT6HhBrgHORNjgEfSju8wnfhjsf/Kve8kvoHcNG4H2rH/sLUA8Bjdmyioif [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string ShowClub {
            get {
                return ResourceManager.GetString("ShowClub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAXEgAAFxIBZ5/SUgAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAA14SURBVHic7Zx/cFzVdcc/5739oV1JXv2wftqSZVm2cUxJSmj44RjSJpOEQIs7IfEMmWlsN8OvtA4lDWSGdoApE5pJZtop4JRhQATTduLJZKalpDBNMbgkYAPGLg4RyDL+HUvWT0ta7e7bfad/rHffriy8b3ffymai71/v3nvuueeed++595573oMFLGABC1jAAkqElMtAf1nTTNJ6G2gvlcfEsEEsmhYlUMXxhq9EO8qVa75glMtA1k0NIfafAgkP5PnIoWwFAsi11h6Ev/GC10cNnigQgPXxHwL/7hm/jwg8U6AIihHfDBz2iudHAd6NQEDWM4bYG/kdsodlr8JzQV+pegj0Prf0uauwP8hg38nQ [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string ShowL {
            get {
                return ResourceManager.GetString("ShowL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на iVBORw0KGgoAAAANSUhEUgAAAFAAAABQCAYAAACOEfKtAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAN1wAADdcBQiibeAAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAeMSURBVHic7ZttbBt3Hce/9+DznZ/jPPihdpImtROnJEvbNE2WVGu7Mdi6lQJFiAcJAdJ4AxITAlEKLwCJwpBgaLxATJtEgYG2F0xIW6qpFU01qWJo3ZLlOXWWtHYcO/VD7LMdO/EdLyajNmpI2ntK4D6SJcvyfX8/f3z+n+/+/wN0dHR0dHR0dHR0dHR0dP6/IKpPnjn7a1HLRnYbvz//LAEA9J0vfvfst7XpZpfxy/PP/+c5qWEf/xPoAiWiC5SILlAiukCJ6AIloguUiC5QIrpAiegCJUJv/RZ1KGWWsXLjPaxMvYPV2xFUVgtYWy0ABAnGYoOjvQ8NR54AV7dH61bvQnOB2flxxC7/GblbM3B7 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string ShowPlayer {
            get {
                return ResourceManager.GetString("ShowPlayer", resourceCulture);
            }
        }
    }
}
